using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;

namespace Sesh_Box_Lambda
{
    class PicoloRules
    {
        string gameVersion = "getting started";

        string randomParticipentName = "Ciaran";
        int beverageConsumption = 5;
        Random rnd = new Random();
        List<int> randomNumberCheck = new List<int>();

        public string GameVersion { get => gameVersion; set => gameVersion = value; }

        public string Rules()
        {

            List<string> gettingSillyRules = new List<string>(new string[] {
                randomParticipentName + ", imitate a guy taking a shit or drink " + beverageConsumption + " times",
                randomParticipentName + ", show us your balls or drink " + beverageConsumption + " times",
                "The last person to shout bitch, finish your drink!",
                randomParticipentName + " arm wrestle " + randomParticipentName + ", the loser drinks " + beverageConsumption + " times. Or if you want to chicken out, you drink " + beverageConsumption + " times",
                "The last person to shout " + randomParticipentName + ", lick my balls!, drink " + beverageConsumption + " times",
                "The first to burp gives out " + beverageConsumption + " sips",
                "The youngest person to lose their virginity, give out " + beverageConsumption + " sips",
                "The person who began masturbating the youngest, give out " + beverageConsumption + " sips",
                randomParticipentName + ", pick a booger or drink " + beverageConsumption + " times",
                randomParticipentName + ", if you have less than two balls give out " + beverageConsumption + " sips",
                randomParticipentName + ", show your pubes or drink " + beverageConsumption + " times",
                "At the start of each rule until the end of the game, the first person to audibly fart gives out  sips",
                "The most muscular person between " + randomParticipentName + " and " + randomParticipentName + " can give out " + beverageConsumption + " sips",
                "Between " + randomParticipentName + " and " + randomParticipentName + ", whoever pooped most recently can give out " + beverageConsumption + " sips",
                "The person who gave a blowjob most recently gives out " + beverageConsumption + " sips",
                randomParticipentName + ", if you've ever given someone a blowjob, drink " + beverageConsumption + " times",
                randomParticipentName + ", lick the ground or drink " + beverageConsumption + " times",
                "Push up competition between " + randomParticipentName + " and " + randomParticipentName + ". The loser drinks " + beverageConsumption + " times. Or if you want to chicken out, you drink " + beverageConsumption + " times",
                "The person who masturbated most recently, give out " + beverageConsumption + " sips",
                randomParticipentName + ", put your face on " + randomParticipentName + "'s butt or drink " + beverageConsumption + " times",
                randomParticipentName + ", pour a bit of your drink into each player's glass",
                "Everybody pour some of your drink into " + randomParticipentName + "'s glass",
                randomParticipentName + ", lick " + randomParticipentName + "'s ear or finish your drink",
                randomParticipentName + " and " + randomParticipentName + ", take off your pants or finish your drink",
                randomParticipentName + ", finish your drink or fill it to the top",
                randomParticipentName + ", take the glass of the player to your right and feed them " + beverageConsumption + " drinks",
                "The first person to correctly say the year that Jesus was born, give out " + beverageConsumption + " sips",
                randomParticipentName + ", put an ice cube in your underwear for five minutes",
                randomParticipentName + ", pinch " + randomParticipentName + "'s nipples or drink " + beverageConsumption + " times",
                randomParticipentName + ", show your ass to everyone",
                randomParticipentName + " drink " + beverageConsumption + " times upside down (hands on the ground, legs in the air) " + randomParticipentName + " and " + randomParticipentName + " will help keep you balanced",
                "If you would sleep with the person to your left, drink " + beverageConsumption + " times",
                "If you would sleep with the person to your right, drink " + beverageConsumption + " times",
                "If you check the toilet paper after wiping your ass, drink " + beverageConsumption + " times",
                randomParticipentName + " if you have ever thought about a cousin while masturbating, drink " + beverageConsumption + " times",
                "If you've had sex in the last week, drink " + beverageConsumption + " times",
                randomParticipentName + ", if you've crossed swords with a cousin, drink " + beverageConsumption + " times",
                randomParticipentName + ", if you've ever masturbated into a sock, drink " + beverageConsumption + " times",
                randomParticipentName + ", put a finger in " + randomParticipentName + "'s nose. Otherwise, drink " + beverageConsumption + " times",
                randomParticipentName + ", drink as many times as dicks that you have sucked",
                "Whoever has had the fastest orgasm, give out " + beverageConsumption + " drinks",
                "If you've slept with  different people in the same week, drink " + beverageConsumption + " times",
                "If you've slept with  different people in the same day, drink " + beverageConsumption + " times",
                randomParticipentName + ", stroke " + randomParticipentName + "'s crotch. If you don't, everyone has to drink " + beverageConsumption + " times",
                "If you've ever had more than  friends with benefits, raise your glass and say long live fuck buddies! and down your drink",
                "If you want to have sex tonight, give out " + beverageConsumption + " sips",
                "If you've ever cheated in a relationship, sneakily drink  time. Don't worry, no one saw you take that sip.",
                randomParticipentName + ", do a pushup with one hand or drink " + beverageConsumption + " times",
                randomParticipentName + ", act out deep throating or finish your drink",
                randomParticipentName + ", pretend you are masturbating for  seconds or finish your drink",
                "Drink " + beverageConsumption + " times if you have shown your penis or boobs on snapchat",
                randomParticipentName + ", drink " + beverageConsumption + " times without putting your lips on your glass",
                randomParticipentName + ", put something edible in " + randomParticipentName + "'s glass. When the drink is finished, he/she will have to eat it",
                randomParticipentName + " and " + randomParticipentName + ", down your drinks. The winner gets immunity for  minutes",
                "If you have ever masturbated to GQ, drink " + beverageConsumption + " times",
                "Someone put a pubic hair in " + randomParticipentName + "'s glass before he/she can finish chugging it",
                "If you've ever fingered you own ass, drink " + beverageConsumption + " times",
                randomParticipentName + ", drink as many times as the number of times you masturbated in the last 7 days",
                "If you've ever had sex with a hooker, give out " + beverageConsumption + " sips",
                randomParticipentName + ", drink " + beverageConsumption + " times in cumshot mode, (don't let the glass touch your lips)",
                "If you have masturbated to a cartoon, drink " + beverageConsumption + " times",
                randomParticipentName + ", either let " + randomParticipentName + " change your Facebook profile picture until the end of the game, or finish your drink",
                randomParticipentName + ", say " + randomParticipentName + "’s name by burping or drink " + beverageConsumption + " times.",
                randomParticipentName + ", you choose: add liquor to your glass or drink " + beverageConsumption + " times.",
                randomParticipentName + ", drink as many sips as you'd like. " + randomParticipentName + " and " + randomParticipentName + " will drink double.",
                "The next player who has to drink will triple his/her number of drinks!",
                "The next player who has to drink will quadruple his/her number of drinks!",
                "For girls, the last one to have your period, drink " + beverageConsumption + " times.",
                "If you have burped or farted since the beginning of the game, drink " + beverageConsumption + " times.",
                randomParticipentName + ", allow one player to take a closeup picture of your crotch with your phone or drink " + beverageConsumption + " times.",
                "The last player to have tasted a girl's cum, give out " + beverageConsumption + " sips.",
                "If you've had sex with a prostitute once in your life, give out " + beverageConsumption + " sips. ",
                "If you've had more longterm relationships than friends with benefits, give out " + beverageConsumption + " sips.",
                "If you have a penis under  inches, drink " + beverageConsumption + " times.",
                "If you took a shit today, drink " + beverageConsumption + " times.",
                randomParticipentName + ", choose between drinking " + beverageConsumption + " times or kissing " + randomParticipentName + "’s feet without socks or shoes on.",
                randomParticipentName + ", if you can do 5 push-ups, " + randomParticipentName + " has to drink " + beverageConsumption + " times.",
                randomParticipentName + ", feed the arm holding your drink under your leg and then drink " + beverageConsumption + " times.",
                "The sillier person between " + randomParticipentName + " and " + randomParticipentName + ", drink " + beverageConsumption + " times.",
                randomParticipentName + ", if " + randomParticipentName + " counts to 5 before you can spin around  times, you have to finish your glass! Ready, set, go!",
                randomParticipentName + ", if you have ever puked on someone, drink " + beverageConsumption + " times. If not, give out " + beverageConsumption + " sips.",
                "If you've ever masturbated thinking of a friend, drink " + beverageConsumption + " times.",
                "The first player to post a Snapchat story, give out " + beverageConsumption + " sips.",
                randomParticipentName + ", if you've ever beaten up somebody, drink " + beverageConsumption + " times.",
                randomParticipentName + ", if you've ever gotten beat up, give out " + beverageConsumption + " sips.",
                "If you've ever done a shit n' shower (poop without wiping and directly take a shower), drink " + beverageConsumption + " times.",
                "If you've ever swallowed a guy's cum, drink " + beverageConsumption + " times.",
                "If you've ever given money to a homeless person, give out " + beverageConsumption + " sips",
                "If you've ever spied on one of your neighbors to see them naked, drink " + beverageConsumption + " times.",
                "The first person to show your junk, give out " + beverageConsumption + " sips!",
                "Drink " + beverageConsumption + " times if you've ever drawn a tree",
                "Drink " + beverageConsumption + " times if you shit your pants this year, racing stripes count",
                "Drink " + beverageConsumption + " times if you were on a porn site yesterday",
                "Drink " + beverageConsumption + " times if you pissed yourself this year",
                "Drink " + beverageConsumption + " times if you've ever pissed in a bathroom sink",
                "Drink " + beverageConsumption + " times if you've ever pissed in a sink",
                "Drink " + beverageConsumption + " times if you've ever re-swallowed your vomit",
                "Drink " + beverageConsumption + " times if you've ever fantasized about a cartoon character",
                "Drink " + beverageConsumption + " times if you've ever looked at your anus in the mirror",
                "Those who shave their anus drink " + beverageConsumption + " times",
                randomParticipentName + ", sniff " + randomParticipentName + "'s arm pits or drink " + beverageConsumption + " times",
                randomParticipentName + ", scratch " + randomParticipentName + "'s back or drink " + beverageConsumption + " times",
                randomParticipentName + ", choose between drinking one sip from each player's drink or drink 5 times from your own",
                randomParticipentName + " and " + randomParticipentName + " have a biggest biceps contest, players judge the loser that'll drink " + beverageConsumption + " times",
                randomParticipentName + ", sniff " + randomParticipentName + "'s underwear or drink " + beverageConsumption + " times",
                "Drink " + beverageConsumption + " times if you've ever been fingered in the ass",
                randomParticipentName + ", spin around 5 times and drink each time you face the stupid guys who first looked at you",
                "Those who have ever tasted a few drops of piss during foreplay drink " + beverageConsumption + " times",
                randomParticipentName + " and " + randomParticipentName + " are in a silly contest! Slap yourself in the face as hard as you can, the hardest wins! The loser drink " + beverageConsumption + " times",
                randomParticipentName + " and " + randomParticipentName + " are in a silly contest! Slap yourself on the butt as hard as you can, the hardest wins! The loser drink " + beverageConsumption + " times",
                "Silly contest with " + randomParticipentName + " vs. " + randomParticipentName + " from now on! The winner is the one who lasts longer with their arms in the air, the loser drinks " + beverageConsumption + " times",
                "Silly contest with " + randomParticipentName + " vs. " + randomParticipentName + " from now on! The winner is the one who lasts longer standing on one leg, the loser drinks " + beverageConsumption + " times",
                "Silly contest with " + randomParticipentName + " vs. " + randomParticipentName + " from now on! The winner is the one who lasts longer spinning around, the loser drinks " + beverageConsumption + " times",
                "Silly contest with " + randomParticipentName + " vs. " + randomParticipentName + " from now on! The winner is the one who lasts longer doing squats, the loser drinks " + beverageConsumption + " times",
                "Silly contest with " + randomParticipentName + " vs. " + randomParticipentName + " from now on! The winner is the one who lasts longer saying I love ass fucking without laughing, the loser drinks " + beverageConsumption + " times",
                "Silly contest with " + randomParticipentName + " vs. " + randomParticipentName + " from now on! The winner is the one who lasts longer saying I am ugly without laughing, the loser drinks " + beverageConsumption + " times",
                "Silly contest with " + randomParticipentName + " vs. " + randomParticipentName + " from now on! The winner is the one who lasts longer saying I am stupid without laughing, the loser drinks " + beverageConsumption + " times",
                "Silly contest with " + randomParticipentName + " vs. " + randomParticipentName + " from now on! The winner is the one who lasts longer doing a plank, the loser drinks " + beverageConsumption + " times",
                randomParticipentName + " and " + randomParticipentName + " are having a silly contest! Text as many contacts as you can in  minute, the one to send most wins! The loser drink " + beverageConsumption + " times",
                "Silly contest with " + randomParticipentName + " vs. " + randomParticipentName + " from now on! The winner is the one who lasts longer holding his/her tongue with two fingers, the loser drinks " + beverageConsumption + " times",
                randomParticipentName + " weighs one of the male player's balls or drinks " + beverageConsumption + " times",
                "Drink " + beverageConsumption + " times if you've ever farted while having sex",
                "Guys, last one to take his shirt off drinks " + beverageConsumption + " times!",
                randomParticipentName + ", challenge " + randomParticipentName + " to any action you want. If he or she refuses it's a " + beverageConsumption + " sips penalty!",
                "Bearded people drink " + beverageConsumption + " times!",
                "If you've taken a shit in the ocean drink " + beverageConsumption + " times",
                "Drink " + beverageConsumption + " times if you've taken a shit on the street",
                randomParticipentName + ", change the Facebook status of any player. If it reaches 5 likes before the end of the game you'll decide who will finish their drink, you drink as many times as there are likes otherwise...",
                randomParticipentName + ", imitate a drunk dog barking and drink " + beverageConsumption + " times!",
                 randomParticipentName + " drinks " + beverageConsumption + " times while " + randomParticipentName + " blowing in " + randomParticipentName + "'s face",
                randomParticipentName + ", stand 5 minutes with two fingers in your ears or drink " + beverageConsumption + " times on every new event",
                randomParticipentName + ", count to  loudly or drink " + beverageConsumption + " times",
                randomParticipentName + " must get on " + randomParticipentName + "'s back and ride him/her like a cowboy/cowgirl for  seconds, " + beverageConsumption + " sips if you lose or refuse",
                randomParticipentName + " break an ice cube on your forehead or drink " + beverageConsumption + " times",
                randomParticipentName + ", let " + randomParticipentName + " break an ice cube on your forehead, refuse and you'll drink " + beverageConsumption + " times",
                "I hold you, you hold me, by our little goatee, the first one of us two, who will laugh, will finish his drink " + randomParticipentName + " and " + randomParticipentName + " come on!",
                randomParticipentName + ", what's the last thing that went in your ass? Answer and drink " + beverageConsumption + " times!",
                "Drink " + beverageConsumption + " times if you're ready to finish the game totally naked",
                "Drink " + beverageConsumption + " times if you've ever farted loudly in front of strangers",
                "Drink " + beverageConsumption + " times if you've ever farted on purpose in front of strangers",
                "Drink " + beverageConsumption + " times if you've ever eaten pet food",
                "Drink " + beverageConsumption + " times if you've ever had sex in front of your pet",
                "Drink " + beverageConsumption + " times if you've ever had sex while riding public transportation",
                "Drink " + beverageConsumption + " times if you still have some nude pictures of your ex",
                "Drink " + beverageConsumption + " times if you have nude pictures of your boyfriend or girlfriend",
                "Drink " + beverageConsumption + " times if you've ever bought porn magazines",
                "Drink " + beverageConsumption + " times if you've ever taken a golden shower",
                "If you've scored with a MILF or a DILF, drink " + beverageConsumption + " times",
                randomParticipentName + ", show your anus or drink " + beverageConsumption + " times",
                "Drink " + beverageConsumption + " times if you've fucked someone and then forgot their name",
                "Virgin anuses drink " + beverageConsumption + " times",
                "Silly contest between " + randomParticipentName + " and " + randomParticipentName + ", don't block the game! Shake hands, the first one to give up down their drink",
                "The first one to show their balls give out " + beverageConsumption + " sips!",
                "Give out " + beverageConsumption + " sips if you've ever pissed on a meal before serving it",
                "Give out " + beverageConsumption + " sips if you've ever put fruit or vegetables into your partner. You know what we mean",
                "Players with less than half of their drink left, down it!",
                "If you cut your toe nails this week drink " + beverageConsumption + " times",
                "Snorers in the room drink " + beverageConsumption + " times while snoring",
                "Drink " + beverageConsumption + " times if you've ever pissed on someone",
                "Drink " + beverageConsumption + " times if you've ever tortured bugs with a magnifying glass",
                "Drink " + beverageConsumption + " times if you've ever turned a fly into a fireball with aerosol and a lighter",
                "Drink " + beverageConsumption + " times if you've ever torn off a fly's wings",
                "Drink " + beverageConsumption + " times if you've ever shit yourself in class",
                "Drink " + beverageConsumption + " times if you've ever pissed your pants in class",
                "Drink " + beverageConsumption + " times if you've ever googled fart domination",
                "Drink " + beverageConsumption + " times if you've ever googled  girls  cup",
                "Drink " + beverageConsumption + " times if you've ever googled  guys  stump",
                "Drink " + beverageConsumption + " times if you've ever watched chinese porn where the scene takes place in a bus with  guys",
                "Everybody take " + beverageConsumption + " sips. Except " + randomParticipentName + ", who makes great blowjobs with his/her ass",
                "Guys who have heard a pussy fart drink " + beverageConsumption + " times",
                "Girls who have let out a pussy fart while having sex drink " + beverageConsumption + " times",
                randomParticipentName + " put an ice cube in his/her asshole or drink " + beverageConsumption + " times",
                randomParticipentName + ", drink as many sips as pussies you have licked ",
                randomParticipentName + ", go ring the neighbor's doorbell or drink " + beverageConsumption + " times",
                randomParticipentName + ", pour some of your drink into your underwear or drink " + beverageConsumption + " times",
                randomParticipentName + ", text one of your contacts with I shit in my pants once again, or drink " + beverageConsumption + " times",
                randomParticipentName + ", go piss in the sink or drink " + beverageConsumption + " times",
                randomParticipentName + ", put your face in toilet water or drink " + beverageConsumption + " times",
                randomParticipentName + ", pour some of your drink over your head or drink " + beverageConsumption + " times",
                randomParticipentName + ", put a bathrobe on and go ask the neighbor for some ice cubes for your drink, or drink " + beverageConsumption + " times",
                randomParticipentName + ", beauty mask on! Spread some toothpaste on your face or drink " + beverageConsumption + " times",
                "The one who has the biggest boobs gives out " + beverageConsumption + " sips",
                randomParticipentName + ", eat one of your boogers or drink " + beverageConsumption + " times",
                randomParticipentName + ", drink from every bottle on the table",
                randomParticipentName + ", send a picture of your dick or pussy to  contacts or drink " + beverageConsumption + " times",
                randomParticipentName + ", hold a handstand for 5 seconds with your pants around your ankles or drink " + beverageConsumption + " times",
                randomParticipentName + ", do a cartwheel or drink " + beverageConsumption + " times",
                randomParticipentName + ", lick " + randomParticipentName + "'s butt crack or drink " + beverageConsumption + " times",
                "Drink " + beverageConsumption + " times if you've ever bought an enema syringe",
                "Drink " + beverageConsumption + " times if you've ever used a water jet to cum",
                randomParticipentName + " take a sip of your drink and spit it in " + randomParticipentName + "'s glass",
                "Drink " + beverageConsumption + " times if you've ever googled bukkake carrot",
                "Girls who have lost a condom in their cherry drink " + beverageConsumption + " times",
                "Girls who have lost a tampon in their pussy drink " + beverageConsumption + " times",
                randomParticipentName + ", explain how to do a no wiper on the toilet, and drink " + beverageConsumption + " times",
                randomParticipentName + " eats an ice cube or drinks " + beverageConsumption + " times",
                randomParticipentName + ", choose a four-eyed player and put a fingerprint on his/her glasses, " + beverageConsumption + " sips in case of refusal. If no one is near/farsighted, give out " + beverageConsumption + " sips",
                randomParticipentName + ", if you have a clitoris drink " + beverageConsumption + " times, give out " + beverageConsumption + " sips otherwise",
                randomParticipentName + ", if you have testes drink " + beverageConsumption + " times, give out " + beverageConsumption + " sips otherwise",
                randomParticipentName + ", eat some player's hair, " + beverageConsumption + "-sip penalty in case of a refusal"
            });

            List<string> calienteRules = new List<string>(new string[] {
                randomParticipentName + "  if you are a girl lick your finger in an erotic way. If you are a guy do a cunnilingus with two fingers. Or finish your drink",
                "If you've had sex in a public place drink " + beverageConsumption + "  times",
                randomParticipentName + "  pretend you are having an orgasm for  seconds or finish your drink",
                "If you've had a threesome drink " + beverageConsumption + "  times. If all three people are in the room right now drink double!",
                "Girls pull up your thongs",
                randomParticipentName + "  and  " + randomParticipentName + "  cuddle for the next 5 minutes",
                "If you've had Skype sex drink " + beverageConsumption + "  times",
                "If you've ever thought of someone else during sex drink " + beverageConsumption + "  times",
                "If you would sleep with someone else in this room right now drink " + beverageConsumption + "  times",
                "Drink " + beverageConsumption + "  times if you've had sex on the first date",
                "If you love oral drink " + beverageConsumption + "  times",
                "If you've made a sex tape drink " + beverageConsumption + "  times",
                "If you think  " + randomParticipentName + "  is a good bang drink " + beverageConsumption + "  times",
                randomParticipentName + "  get your finger sucked by  " + randomParticipentName + "  or drink " + beverageConsumption + "  times",
                "If you have given someone a rimjob drink " + beverageConsumption + "  times",
                "Everyone unbutton your shirts and drink once for each button",
                randomParticipentName + "  take an item of clothing off of  " + randomParticipentName + "  or drink " + beverageConsumption + "  times",
                "If you have ever been caught masturbating drink " + beverageConsumption + "  times",
                "If you shave your intimate areas drink " + beverageConsumption + "  times",
                " Drink " + beverageConsumption + "  times if you've visited a porn site in the last two weeks",
                "If you like dirty talk drink " + beverageConsumption + "  times",
                randomParticipentName + "  how many drinks would it take for you to sleep with  " + randomParticipentName + " ? Answer and drink " + beverageConsumption + "  times",
                randomParticipentName + "  who do you think would give the best head out of the people in the room? Answer and drink " + beverageConsumption + "  times",
                "If you've ever roleplayed to keep things spicy drink " + beverageConsumption + "  times",
                randomParticipentName + "  simulate an orgasm before every drink until told otherwise",
                randomParticipentName + "  you no longer have to simulate an orgasm before every drink",
                randomParticipentName + "  give " + beverageConsumption + "  sips to the sexiest person in the room. (Yes you are sexy but pick someone other than yourself)",
                "If you've ever slept with someone and not remembered their name drink " + beverageConsumption + "  times",
                "If you've had sex in a hotel drink " + beverageConsumption + "  times",
                randomParticipentName + "  act out doggy style for 5 seconds or drink " + beverageConsumption + "  times",
                "If you've never had sex in a car drink " + beverageConsumption + "  times",
                randomParticipentName + "  name a sexual act that you haven't done. Anybody who has done it drink " + beverageConsumption + "  times",
                "If you've ever taken a pole dancing class drink " + beverageConsumption + "  times",
                "If you've ever gotten a sex toy as a birthday present drink " + beverageConsumption + "  times",
                "If you've hooked up with anyone in the room both of you drink " + beverageConsumption + "  times",
                "If you are eskimo brothers/sisters with anyone in the room both of you drink " + beverageConsumption + "  times",
                randomParticipentName + "  if you show us one of your tits  " + randomParticipentName + "  has to drink " + beverageConsumption + "  times. If not you drink " + beverageConsumption + "  times.",
                randomParticipentName + "   " + randomParticipentName + "   " + randomParticipentName + "  and  " + randomParticipentName + " - pretend to gangbang  " + randomParticipentName + "  or drink " + beverageConsumption + "  times.",
                randomParticipentName + "  either kiss  " + randomParticipentName + " 's feet or drink " + beverageConsumption + "  times.",
                randomParticipentName + "  if you kiss  " + randomParticipentName + "  on the cheek everybody takes " + beverageConsumption + "  sips",
                "Everyone drink for the number of orgasms you've had this week including ones resulting from a self-performance.",
                "If you haven't had sex this week drink " + beverageConsumption + "  times",
                "If you've had sex with someone more than 5 years older than you drink " + beverageConsumption + "  times",
                "If you've had sex with someone more than 5 years younger than you drink " + beverageConsumption + "  times",
                "If  " + randomParticipentName + "  and  " + randomParticipentName + "  kiss each of you can give you " + beverageConsumption + "  sips. If not you each have to drink " + beverageConsumption + "  times.",
                "If you've ever sexted (sex texting) with someone drink " + beverageConsumption + "  times.",
                "The first person who can show us a text about sex can give out " + beverageConsumption + "  sips",
                "If you've ever been unable to get it up during a sexual encounter drink " + beverageConsumption + "  times.",
                "If you've had sex with another player in the room drink " + beverageConsumption + "  times",
                randomParticipentName + "  if you've had sex more than 4 times in one day give out " + beverageConsumption + "  drinks. If not drink " + beverageConsumption + "  times.",
                "If you've ever fantasized about a friend's partner drink " + beverageConsumption + "  times",
                "If you've ever sent sexual pictures to someone drink " + beverageConsumption + "  times",
                "If you've ever licked or eaten food off someone drink " + beverageConsumption + "  times.",
                "If you've ever had sex in your parent's bed drink " + beverageConsumption + "  times.",
                "If you've ever screamed out your partner's name while having sex drink " + beverageConsumption + "  times.",
                "If you've had an orgasm in less than 3 minutes drink " + beverageConsumption + "  times.",
                randomParticipentName + "  take one item of clothing off of  " + randomParticipentName + "  or drink " + beverageConsumption + "  times.",
                "If you've had sex while you or your partner was on her period drink " + beverageConsumption + "  times.",
                "Who's better in bed between  " + randomParticipentName + "  and  " + randomParticipentName + " ? The winner drinks " + beverageConsumption + "  times.",
                "If you've ever had a purely sexual relationship with a friend drink " + beverageConsumption + "  times.",
                "If your first time hurt like a motherfucker drink " + beverageConsumption + "  times",
                randomParticipentName + "  if having sex with  " + randomParticipentName + "  wouldn't bother you give out " + beverageConsumption + "  sips",
                randomParticipentName + "  if you've secretly been in love with  " + randomParticipentName + "  drink " + beverageConsumption + "  times together",
                 randomParticipentName + "  pinch  " + randomParticipentName + " 's tits or he/she drinks " + beverageConsumption + "  times",
                "If you've ever stuck an object into your partner during sex drink " + beverageConsumption + "  times.",
                "If you've every cried out the wrong person's name while having sex drink " + beverageConsumption + "  times.",
                randomParticipentName + "  choose someone and you must now stare into his/her eyes until we tell you to stop!",
                randomParticipentName + "  you can stop staring deeply into your friend's eyes!",
                "Everytime you speak you must stroke your chest!",
                "You can all stop stroking your chests! (And if you want you can start stroking someone else's just a suggestion)",
                beverageConsumption + "  times",
                "Drink " + beverageConsumption + "  times if you've ever had sex thanks to a dating website",
                "The last person to visit a porn site gives out " + beverageConsumption + "  sips",
                "The one who has had the most sex thanks to a dating website give out " + beverageConsumption + "  sips",
                "Drink " + beverageConsumption + "  times if you've ever been scratched while having sex",
                "Drink " + beverageConsumption + "  times if you've ever held a sex toy in your hands",
                "Drink " + beverageConsumption + "  times if you've ever used objects while having sex",
                "Drink " + beverageConsumption + "  times if you've ever gotten excited by a professional massage",
                randomParticipentName + "  licks  " + randomParticipentName + " 's nose or drink " + beverageConsumption + "  times",
                "Drink " + beverageConsumption + "  times if you've ever spit while going down on your partner.",
                "Drink " + beverageConsumption + "  times if you've given a blowjob this month",
                randomParticipentName + "  give a head massage to  " + randomParticipentName + "  or drink " + beverageConsumption + "  times",
                randomParticipentName + "  get your crotch sensually touched by  " + randomParticipentName + "  or drink " + beverageConsumption + "  times",
                "Drink " + beverageConsumption + "  times if you've given a blowjob this week",
                "Drink " + beverageConsumption + "  times if you've ever had an object in your anus or vagina",
                randomParticipentName + "  kiss  " + randomParticipentName + "  on the nose or drink " + beverageConsumption + "  times",
                "Drink " + beverageConsumption + "  times if you are a naughty one and have insulted your partner while having sex",
                randomParticipentName + "  chooses two people to kiss one another " + beverageConsumption + "  sips for each if one of them refuses",
                "Drink " + beverageConsumption + "  times if you've ever seen a friend cheat on their boyfriend/girlfriend",
                "Drink " + beverageConsumption + "  times if you have ever dated your friend's ex. ",
                randomParticipentName + "  if the last time you had sex you used condoms give out " + beverageConsumption + "  sips drink them otherwise",
                randomParticipentName + "  would you rather have oral anal or vaginal sex? Answer and drink " + beverageConsumption + "  times",
                "Drink " + beverageConsumption + "  times if you've ever been insulted while having sex",
                " get on all fours and arch your back until told otherwise!",
                "  can be in a comfortable position again",
                randomParticipentName + "  you're the cop! You can body-search anyone anywhere! " + beverageConsumption + " -sips penalty in case of refusal!",
                randomParticipentName + "  you're not the cop anymore you can drink " + beverageConsumption + "  times you pervert!",
                randomParticipentName + "  is Cupid! You choose who kisses or hugs who " + beverageConsumption + " -sips penalty in case of refusal",
                randomParticipentName + "  you're not Cupid anymore. ",
                " Drink " + beverageConsumption + "  times if you like being watched while you make love" });

            List<string> gettingStartedRules = new List<string>(new string[]{ randomParticipentName + ", you have two minutes to finish your drink",
                randomParticipentName + ", say something you have NEVER done. Those who have done it, drink " + beverageConsumption + " times",
                randomParticipentName + ", give out " + beverageConsumption + " sips",
                randomParticipentName + ", drink " + beverageConsumption + " times",
                randomParticipentName + ", say " + randomParticipentName + "'s birthday or drink " + beverageConsumption + " times",
                randomParticipentName + ", take off an item of clothing or drink " + beverageConsumption + " times",
                randomParticipentName + ", lick the forearm of the person to your left or drink " + beverageConsumption + " times",
                randomParticipentName + ", tell a joke or drink " + beverageConsumption + " times",
                randomParticipentName + " drink " + beverageConsumption + " times from " + randomParticipentName + "'s glass",
                randomParticipentName + " if you know " + randomParticipentName + ", give him/her a kiss",
                randomParticipentName + " if you know " + randomParticipentName + ", lick his/her cheek, or drink " + beverageConsumption + " times",
                randomParticipentName + ", kiss " + randomParticipentName + " or drink " + beverageConsumption + " times",
                randomParticipentName + ", ask " + randomParticipentName + " any question you want, and he/she must answer or finish his/her drink",
                randomParticipentName + ", challenge someone to a thumb war, the loser drinks " + beverageConsumption + " times",
                randomParticipentName + " and " + randomParticipentName + " have a staring war, the loser drinks " + beverageConsumption + " times",
                randomParticipentName + ", tell " + randomParticipentName + " to drink as many times as you want",
                "Stand up! The last player to stand up has to drink " + beverageConsumption + " times",
                randomParticipentName + " give " + beverageConsumption + " sips to " + randomParticipentName + " or " + beverageConsumption + " sips to " + randomParticipentName,
                randomParticipentName + " decides: either " + randomParticipentName + " gives out " + beverageConsumption + " sips or " + randomParticipentName + " gives out " + beverageConsumption + " sips",
                randomParticipentName + ", drink " + beverageConsumption + " times and give out " + beverageConsumption + " sips",
                randomParticipentName + " if you are a girl give out " + beverageConsumption + " sips, otherwise drink them!",
                randomParticipentName + ", the next person you look in the eyes drinks " + beverageConsumption + " times",
                "Whoever removes two items of clothing the fastest can give out " + beverageConsumption + " sips",
                "The first person to lick their elbow gives out  drinks",
                randomParticipentName + " and " + randomParticipentName + " must agree to give one person " + beverageConsumption + " sips",
                "Left handed people drink " + beverageConsumption + " times",
                "Anyone with a phone on the table has to drink " + beverageConsumption + " times",
                "The first person to identify the youngest player, give out " + beverageConsumption + " sips",
                "The person with the fullest glass drinks " + beverageConsumption + " times. Catch up!",
                "The hairiest person has to drink " + beverageConsumption + " times",
                "Everyone with the letter e in their first name drink " + beverageConsumption + " times",
                randomParticipentName + " show everyone the last  photos in your phone or drink " + beverageConsumption + " times",
                "Everyone with brown hair drink " + beverageConsumption + " times",
                "The person who had sex most recently, give out " + beverageConsumption + " sips",
                "The tallest player give out " + beverageConsumption + " sips",
                "All the blondes drink " + beverageConsumption + " times",
                "Everyone younger than " + randomParticipentName + ", drink " + beverageConsumption + " times",
                "Everyone older than " + randomParticipentName + ", drink " + beverageConsumption + " times",
                "Anyone who is taller than " + randomParticipentName + ", drink " + beverageConsumption + " times",
                "Anyone who is shorter than " + randomParticipentName + ", drink " + beverageConsumption + " times",
                "Anyone who is tanner than " + randomParticipentName + ", drink " + beverageConsumption + " times",
                "Anyone more drunk than " + randomParticipentName + ", drink " + beverageConsumption + " times",
                "Anyone less drunk than " + randomParticipentName + " drink " + beverageConsumption + " times",
                "If you have holes in your socks, drink " + beverageConsumption + " times. Also, consider buying new socks.",
                 randomParticipentName + ", give " + randomParticipentName + " free access to your facebook for  minutes or finish your drink",
                "Everyone wearing a thong, drink " + beverageConsumption + " times",
                "Everyone with a tattoo or piercing, drink " + beverageConsumption + " times",
                "Whoever has the biggest hands between " + randomParticipentName + " and " + randomParticipentName + ", drink " + beverageConsumption + " times",
                "The last person to go to the bathroom, drink " + beverageConsumption + " times",
                "Whoever has the darkest underwear between " + randomParticipentName + " and " + randomParticipentName + ", drink " + beverageConsumption + " times. (If you aren't wearing underwear, also drink.)",
                "People with blue eyes, drink " + beverageConsumption + " times",
                 randomParticipentName + ", if your legs aren't shaved drink " + beverageConsumption + " times",
                 randomParticipentName + ", take a sip of your drink without using hands or arms. Good luck",
                 randomParticipentName + " tell a funny story about another player or drink " + beverageConsumption + " times",
                 beverageConsumption + " sips for everyone!",
                "Freeze! The last person to stop moving drinks " + beverageConsumption + " times",
                "The person to the right of " + randomParticipentName + ", drink " + beverageConsumption + " times",
                "The person to the left of " + randomParticipentName + ", drink " + beverageConsumption + " times",
                "Hands up! Last person with their hands in the air drinks " + beverageConsumption + " times",
                "Boomerang boomerang, " + randomParticipentName + " can transfer his/her drinks to any player on the next turn",
                "Anyone who has known " + randomParticipentName + " for less than one month drink " + beverageConsumption + " times",
                "Football fans drink " + beverageConsumption + " times",
                "Stop staring at your phone! The next person to use his/her phone drinks  times",
                "People with iPhones, drink " + beverageConsumption + " times",
                "People with Android phones, drink " + beverageConsumption + " times",
                "People wearing glasses drink " + beverageConsumption + " times",
                "Anyone who hasn't played Picolo before tonight, drink " + beverageConsumption + " times",
                "The last person to smoke weed, drink " + beverageConsumption + " times",
                 randomParticipentName + " drink as much as you want, " + randomParticipentName + " has to drink double",
                "The person with the biggest ass, drink " + beverageConsumption + " times",
                "The person with the strongest drink, drink " + beverageConsumption + " times",
                 randomParticipentName + ", if you are drinking cheaper booze than " + randomParticipentName + ", drink " + beverageConsumption + " times",
                "If your birthday is on an even numbered day, drink " + beverageConsumption + " times",
                "If your birthday is on an odd numbered day, drink " + beverageConsumption + " times",
                "If you don't have " + randomParticipentName + "'s number, drink " + beverageConsumption + " times",
                 randomParticipentName + ", say the name of the last movie you saw in theaters. Everyone who didn't see it drink " + beverageConsumption + " times",
                 randomParticipentName + ", choose your drinking b*tch. You'll be able to transfer your sips to him/her twice in this game",
                 randomParticipentName + ", truth, dare or drink? " + randomParticipentName + ", come up with a question or a dare",
                 randomParticipentName + " and " + randomParticipentName + ", make a cool handshake together. Now you guys can be best friends!",
                "If you can touch your nose with your tongue, give out " + beverageConsumption + " sips",
                "If you're single, give " + beverageConsumption + " sips to one person",
                "People in relationships, give " + beverageConsumption + " sips to one person",
                "The last person to post a Facebook status, drink " + beverageConsumption + " times",
                 randomParticipentName + ", kiss " + randomParticipentName + "'s butt or drink " + beverageConsumption + " times",
                "The first person to pull out a condom, give out " + beverageConsumption + " sips",
                "Lava monster! The last person to still have their feet on the ground drinks " + beverageConsumption + " times",
                 randomParticipentName + ", name an accessory (belt, watch, necklace etc). Everyone wearing this accessory, drinks " + beverageConsumption + " times",
                "But first, let me take a selfie. " + randomParticipentName + " and " + randomParticipentName + " take a picture together with funny faces",
                 randomParticipentName + ", add either a mixer or alcohol to " + randomParticipentName + "'s glass",
                 randomParticipentName + ", if you've ever had to use a leaf instead of toilet paper, drink " + beverageConsumption + " times",
                 randomParticipentName + " drink as many times as there are players",
                 randomParticipentName + ", drink as many times as there are boobs in the room (conversion rate:  boob =  sip)",
                "The last person who threw up on a night out, give out " + beverageConsumption + " sips",
                 randomParticipentName + " and " + randomParticipentName + ", drink " + beverageConsumption + " times together",
                "If you've had an STD, give out " + beverageConsumption + " sips",
                "One by one, refill your glasses, " + randomParticipentName + " you start",
                "The youngest person in the room, give out " + beverageConsumption + " sips",
                "The person with the most Facebook friends, drink " + beverageConsumption + " times",
                 randomParticipentName + ", have you ever had a one night stand? If so, give out " + beverageConsumption + " sips. If not, drink.",
                "Until " + randomParticipentName + " sees his/her name on this screen again, he/she will drink for every new screen",
                "Tag, you're it! The person who is it touches a player who drinks and they become the next it. " + randomParticipentName + ", you're first. Play this till the end!",
                "Anyone with a pack of cigarettes, drink once per cigarette (8 max)",
                "People who aren't drinking hard alcohol, drink " + beverageConsumption + " times",
                "If you've ever mastur*ated to a music video, drink " + beverageConsumption + " times",
                 randomParticipentName + ", let's do three dance moves or drink " + beverageConsumption + " times",
                 randomParticipentName + ", tell us " + randomParticipentName + "'s age or drink " + beverageConsumption + " times",
                 randomParticipentName + ", tell us the zodiac sign of " + randomParticipentName + " or drink " + beverageConsumption + " times",
                 randomParticipentName + ", close your eyes! Now tell us " + randomParticipentName + "'s eye color, or drink " + beverageConsumption + " times",
                 randomParticipentName + ", close your eyes! Now tell us the color of " + randomParticipentName + "'s shoes, or drink " + beverageConsumption + " times",
                 randomParticipentName + ", you have less than  seconds to say the exact number of people in the room. Fail and you drink " + beverageConsumption + " times. ........",
                 randomParticipentName + ", tell us " + randomParticipentName + "'s favorite color or drink " + beverageConsumption + " times",
                "Get your serious face on. The next person who smiles has to drink " + beverageConsumption + " times",
                "The youngest person to get a cell phone, drink " + beverageConsumption + " times",
                "If you can't touch your toes standing up straight, drink " + beverageConsumption + " times",
                "The first person to touch " + randomParticipentName + "'s feet gives out " + beverageConsumption + " sips",
                 randomParticipentName + ", if you stay quiet for  minutes, you can choose someone to finish his/her drink!",
                "The next person who has to drink will double his/her amount of sips!",
                "The first person to say YES can choose someone who must down their drink!",
                "Whoever took a shower most recently, drink " + beverageConsumption + " times",
                 randomParticipentName + ", smile for one minute straight. " + beverageConsumption + " sips if you break your smile.",
                "If you're reading this sentence, drink " + beverageConsumption + " times",
                "If you're hearing someone read out this sentence, drink " + beverageConsumption + " times",
                 randomParticipentName + ", do a  second tap dance or drink " + beverageConsumption + " times",
                randomParticipentName + " has  minutes of buccal immunity (you can let your liver rest by not drinking for  minutes)",
                "The least hairy person body included drinks " + beverageConsumption + " times!",
                "Rank the top  hairiest players: rd place drinks once, nd place drinks twice, and st place drinks thrice!",
                "Rank the top  tallest players: rd place drinks once, nd place drinks twice, and st place drinks thrice!",
                "Rank the top  smartest players: rd place drinks once, nd place drinks twice, and st place drinks thrice!",
                "Rank the top  tannest players: rd place drinks once, nd place drinks twice, and st place drinks thrice!",
                "Rank the top  most generous players: rd place drinks once, nd place drinks twice, and st place drinks thrice!",
                "Rank the  poorest players: rd place drinks once, nd place drinks twice, and st place drinks thrice!",
                "The three amigos: " + randomParticipentName + ", " + randomParticipentName + " and " + randomParticipentName + ", all of you drink " + beverageConsumption + " times!",
                "The first one to come up with an inspirational saying (worthy of a cheesy poster) gives out " + beverageConsumption + " sips!",
                "Sort the  youngest players: youngest drinks once, nd youngest drinks twice, and rd youngest drinks thrice!",
                 randomParticipentName + ", if you've ever streaked in public, give out " + beverageConsumption + " sips. If not, drink " + beverageConsumption + " times.",
                "If you haven't taken a shower today, drink " + beverageConsumption + " times!",
                 randomParticipentName + ", if you are wearing flip flops, give out " + beverageConsumption + " sips. If not, drink " + beverageConsumption + " times.",
                "If you have played on more than  high school or college sports teams, give out " + beverageConsumption + " sips.",
                 randomParticipentName + ", if you have curly hair give out " + beverageConsumption + " sips. If not, drink " + beverageConsumption + " times.",
                "The host of this place, give out " + beverageConsumption + " sips. If there isn't a host, " + randomParticipentName + " give out sips!",
                 randomParticipentName + ", imitate another player. The first person to guess who it is, give out " + beverageConsumption + " sips!",
                 randomParticipentName + ", do an action ordered by " + randomParticipentName + ". If you refuse or can't do it, drink " + beverageConsumption + " times.",
                "If you've ever been on TV, drink " + beverageConsumption + " times.",
                "If you've ever secretly read texts on your significant other's phone, drink " + beverageConsumption + " times!",
                "If you've ever cheated on an exam, drink " + beverageConsumption + " times!",
                "If you've ever posted a status or video on Facebook while drunk, drink " + beverageConsumption + " times!",
                 randomParticipentName + ", if you've ever professed your love for someone in a drunk text, give out " + beverageConsumption + " sips. If not, drink " + beverageConsumption + " times.",
                 randomParticipentName + ", if you've ever napped at work or in class, give out " + beverageConsumption + " sips. If not, drink " + beverageConsumption + " times.",
                 randomParticipentName + ", if you've ever shoplifted, give out " + beverageConsumption + " sips. If not, drink " + beverageConsumption + " times.",
                 randomParticipentName + ", if you feel your alcohol blanket right now, give out " + beverageConsumption + " sips. If not, drink " + beverageConsumption + " times!",
                 randomParticipentName + ", if you've ever been thrown out of a bar or club, give out " + beverageConsumption + " sips. If not, drink " + beverageConsumption + " times.",
                 randomParticipentName + ", if you've ever broken up with somebody by text message, give out " + beverageConsumption + " sips. If not, drink " + beverageConsumption + " times.",
                 randomParticipentName + ", if you've ever lied about your age to get a drink, give out " + beverageConsumption + " sips. If not, drink " + beverageConsumption + " times.",
                 randomParticipentName + ", if you've ever punched or slapped someone when drunk, give out " + beverageConsumption + " sips. If not, drink " + beverageConsumption + " times.",
                "If you've never done a strip tease, drink " + beverageConsumption + " times. Maybe tonight will be the night!",
                 randomParticipentName + ", let " + randomParticipentName + " send a snapchat from your phone or drink " + beverageConsumption + " times!",
                "If you've ever used a scented condom, drink " + beverageConsumption + " times!",
                "If you've ever been drunk  nights in a row, drink " + beverageConsumption + " times!",
                "If you've ever started drinking before am, drink " + beverageConsumption + " times!",
                "If you've ever gone  days in a row without underwear, drink " + beverageConsumption + " times!",
                "Sort the  players with the least facial hair: smoothest baby face drinks once, nd smoothest drinks twice, and rd drinks thrice!",
                "Atheist people drink " + beverageConsumption + " times!",
                "If you believe in ghosts, drink " + beverageConsumption + " times.",
                "If you were drunk yesterday, drink " + beverageConsumption + " times!",
                "If you got reallyyy messed up on your last night out, drink " + beverageConsumption + " times!",
                 randomParticipentName + ", if you think you're cuter than " + randomParticipentName + " drink " + beverageConsumption + " times.",
                 randomParticipentName + ", if you've ever been arrested, drink " + beverageConsumption + " times.",
                 randomParticipentName + ", if you've ever started a fight, drink " + beverageConsumption + " times",
                 randomParticipentName + ", if you've ever been involved in a drunk brawl, drink " + beverageConsumption + " times! ",
                 randomParticipentName + ", if you've had less than  glasses tonight, drink " + beverageConsumption + " times!",
                "Those who drank for the previous rule, drink " + beverageConsumption + " times.",
                "Those who drank for the previous rule, give out " + beverageConsumption + " sips!",
                 randomParticipentName + ", if you drank more than " + beverageConsumption + " glasses tonight, give out " + beverageConsumption + " sips.",
                "If you are studying/studied business or finance, drink " + beverageConsumption + " times!",
                "If you are studying/studied any kind of engineering, drink " + beverageConsumption + " times!",
                "If you are studying/studied marketing, drink " + beverageConsumption + " times!",
                "If you are studying/studied medicine, drink " + beverageConsumption + " times!",
                "If you are studying/studied communication, drink " + beverageConsumption + " times!",
                "If you are studying/studied environmental science, drink " + beverageConsumption + " times!",
                "Those who were on Facebook today, drink " + beverageConsumption + " times!",
                "If you haven't given out drinks yet tonight, give out " + beverageConsumption + " sips!",
                "Between " + randomParticipentName + " and " + randomParticipentName + ", whoever has drank less tonight, drink " + beverageConsumption + " times.",
                "The first person to text a family member right now can give out " + beverageConsumption + " sips!",
                "The next player who has to drink gives out " + beverageConsumption + " sips",
                "Drink " + beverageConsumption + " times if you've ever changed your hair color",
                "Guys who are studying to or currently work in a manual job drink " + beverageConsumption + " times",
                "If you've ever painted your nails drink " + beverageConsumption + " times",
                "If your outfit has only been worn today drink " + beverageConsumption + " times",
                "Drink " + beverageConsumption + " times if you've ever edited your Facebook profile picture to make it look better",
                "Last person to join the party drink " + beverageConsumption + " times",
                "Drink " + beverageConsumption + " times if you've ever hacked another player's Facebook account",
                "Drink " + beverageConsumption + " times if you've ever had your Facebook hacked",
                "Drink " + beverageConsumption + " times if you've ever chatted on MSN",
                "Everyone with an even age send a photo to a person of your choice or drink " + beverageConsumption + " times",
                "Rigth-handed people drink " + beverageConsumption + " times",
                "Those who are sick today drink " + beverageConsumption + " times",
                "Drink " + beverageConsumption + " times if you've ever danced a slow dance without dating or kissing afterwards",
                "Drink " + beverageConsumption + " times if you've ever dated someone after passing them a note in high school",
                "Drink " + beverageConsumption + " times if you've ever had your boyfriend or girlfriend stolen by one of your friends",
                "Drink " + beverageConsumption + " times if you've ever taken a shit in a Turkish toilet" });

            
            int index = 0;
            int randomIndex = rnd.Next(1,100);

            if (!randomNumberCheck.Contains(randomIndex))
            {
                randomNumberCheck.Add(randomIndex);
            }
            else {
                index = randomIndex;
            }

            if (gameVersion == "Caliente")
            {
                return calienteRules[index];
            }
            else if (gameVersion == "getting started")
            {
                return gettingStartedRules[index];
            }
            else if (gameVersion == "geting silly") {
                return gettingSillyRules[index];
            }
            return "Major error with the rule return";
        }
    }
}



